// ------------------------------------------------------------------------------
// <auto-generated>
//	 This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FineCodeCoverage
{
	internal sealed partial class Vsix
	{
		public const string Id = "fcc-f339fe606-9d51-4fca-895c-d50375137b62";
		public const string Name = "Fine Code Coverage";
		public const string Description = @"Highlights unit test code coverage";
		public const string Language = "en-US";
		public const string Version = "1.0.0";
		public const string Author = "Fortune Ngwenya";
		public const string Tags = "visual studio, code coverage, c#, vb, .net core, coverlet, unit test, free, community edition";
	}
}
