// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FineCodeCoverage.Output
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidOutputToolWindowPackageString = "4e91ba47-cd42-42bc-b92e-3c4355d2eb5f";
        public static Guid guidOutputToolWindowPackage = new Guid(guidOutputToolWindowPackageString);

        public const string guidOutputToolWindowPackageCmdSetString = "bedda1f3-0d8f-4f8d-a818-0b5523ee662d";
        public static Guid guidOutputToolWindowPackageCmdSet = new Guid(guidOutputToolWindowPackageCmdSetString);

        public const string guidImagesString = "297e101c-4afa-47b1-b382-087cfb4618b0";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidOutputToolWindowPackageCmdSet1String = "d58a999f-4a1b-42df-839a-cb31a0a4fed7";
        public static Guid guidOutputToolWindowPackageCmdSet1 = new Guid(guidOutputToolWindowPackageCmdSet1String);

        public const string guidImages1String = "8252a6d7-bcf3-4518-ae22-ad20ef8d4b63";
        public static Guid guidImages1 = new Guid(guidImages1String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int OutputToolWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int MyMenuGroup = 0x1020;
        public const int cmdidClearUICommand = 0x0100;
    }
}